# Jupyter notebook generator for exporting analysis sessions
import json
from datetime import datetime
from typing import Any

from .notebook_builder import create_chart_output_cells, to_source_lines


# Generate a valid Jupyter Notebook JSON string from the chat log and datasets
def generate_jupyter_notebook(
    dataset_names: list[str] | str,
    chat_log: list[dict[str, Any]],
    profile_dict: dict[str, Any] | None = None,
) -> str:
    if isinstance(dataset_names, str):
        dataset_list = [dataset_names]
    else:
        dataset_list = list(dataset_names) if dataset_names else ["dataset.csv"]

    cells: list[dict[str, Any]] = []

    # 1. Title and Dataset Overview Header
    timestamp_str = datetime.now().strftime("%B %d, %Y • %I:%M %p")
    dataset_str = ", ".join(f"`{d}`" for d in dataset_list)

    summary_info = ""
    if profile_dict:
        if profile_dict.get("is_multi_dataset"):
            s = profile_dict.get("summary", {})
            total_rows = s.get("total_rows", "N/A")
            mem = s.get("total_memory_mb", "N/A")
            summary_info = (
                f"- **Total Tables:** {len(dataset_list)}\n"
                f"- **Total Combined Records:** {total_rows:,} rows\n"
                f"- **Total Memory Usage:** {mem} MB\n"
            )
        else:
            shape = profile_dict.get("shape", {})
            rows = shape.get("rows", "N/A")
            cols = shape.get("columns", "N/A")
            mem = profile_dict.get("memory_mb", "N/A")
            summary_info = (
                f"- **Records:** {rows:,} rows\n"
                f"- **Features:** {cols} columns\n"
                f"- **Memory Usage:** {mem} MB\n"
            )

    header_md = (
        f"# 📊 CSV Insight Generator — Empirical Analytics Notebook\n\n"
        f"**Generated:** {timestamp_str}  \n"
        f"**Target Datasets:** {dataset_str}  \n\n"
        f"### 📋 Dataset Overview\n"
        f"{summary_info}\n"
        f"> *Note: This notebook contains the reproducible execution trail, code blocks, "
        f"visualizations, and executive briefings generated by the CSV Insight Agent.*"
    )
    cells.append(
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": to_source_lines(header_md),
        }
    )

    # 2. Data Setup and Imports Cell
    load_code_lines = [
        "# Environment Setup & Library Imports\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import plotly.express as px\n",
        "import plotly.graph_objects as go\n",
        "import os\n",
        "\n",
        "# Load Datasets\n",
    ]

    if len(dataset_list) == 1:
        fname = dataset_list[0]
        load_code_lines.append(f"# Load primary dataset\n")
        load_code_lines.append(f"df = pd.read_csv('{fname}')\n")
        load_code_lines.append("print(f'Loaded df with shape: {df.shape}')\n")
        load_code_lines.append("df.head()\n")
    else:
        load_code_lines.append("dfs = {}\n")
        for fname in dataset_list:
            var_name = fname.replace(".", "_").replace(" ", "_").lower()
            load_code_lines.append(f"dfs['{fname}'] = pd.read_csv('{fname}')\n")
            load_code_lines.append(f"df_{var_name} = dfs['{fname}']\n")
        load_code_lines.append("df = next(iter(dfs.values()))  # Default primary\n")
        load_code_lines.append("for name, d in dfs.items():\n")
        load_code_lines.append("    print(f'Table: {name} -> shape {d.shape}')\n")

    cells.append(
        {
            "cell_type": "code",
            "execution_count": 1,
            "metadata": {},
            "outputs": [],
            "source": load_code_lines,
        }
    )

    # 3. Conversation Q&A and Analysis Turns
    execution_counter = 2
    turn_index = 1

    i = 0
    while i < len(chat_log):
        entry = chat_log[i]
        if entry.get("role") == "user":
            question_text = entry.get("content", "").strip()

            assistant_entry = None
            if i + 1 < len(chat_log) and chat_log[i + 1].get("role") in ["agent", "assistant"]:
                assistant_entry = chat_log[i + 1]
                i += 1

            question_md = (
                f"## 💬 Analysis Turn {turn_index}: Business Inquiry\n\n"
                f"> **User Question:** *\"{question_text}\"*\n"
            )
            cells.append(
                {
                    "cell_type": "markdown",
                    "metadata": {},
                    "source": to_source_lines(question_md),
                }
            )

            if assistant_entry:
                code_snippets = assistant_entry.get("code") or []
                charts = assistant_entry.get("charts") or []
                content = assistant_entry.get("content", "").strip()

                for snippet_idx, code_snippet in enumerate(code_snippets, 1):
                    code_outputs: list[dict[str, Any]] = []

                    if snippet_idx == len(code_snippets) and charts:
                        code_outputs = create_chart_output_cells(charts)

                    cells.append(
                        {
                            "cell_type": "code",
                            "execution_count": execution_counter,
                            "metadata": {},
                            "outputs": code_outputs,
                            "source": to_source_lines(code_snippet),
                        }
                    )
                    execution_counter += 1

                if content:
                    report_md = (
                        f"### 📋 Executive Briefing (Turn {turn_index})\n\n"
                        f"{content}\n"
                    )
                    cells.append(
                        {
                            "cell_type": "markdown",
                            "metadata": {},
                            "source": to_source_lines(report_md),
                        }
                    )

            turn_index += 1
        i += 1

    # 4. Notebook Footer Note
    footer_md = (
        "---\n\n"
        "### 🔒 Reproducibility & Audit Verification\n\n"
        "All analytical computations and code scripts in this notebook were formulated and validated "
        "by the **CSV Insight Agent**. You can run all cells from top to bottom (`Kernel -> Restart & Run All`) "
        "to reproduce the empirical findings and interactive charts."
    )
    cells.append(
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": to_source_lines(footer_md),
        }
    )

    notebook_dict: dict[str, Any] = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.10.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor: 5": None,
        "nbformat_minor": 5,
    }

    return json.dumps(notebook_dict, indent=2, default=str)


# Backward compatibility aliases
_to_source_lines = to_source_lines
